name: Build for mac

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout extension
        uses: actions/checkout@v3

      - name: Build
        run: cargo build --verbose

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: MacOS
          path: target/clear-wired-selection
          retention-days: 7